### ISSUE TITLE
Publish a crate name with a namespace separator

### ISSUE THREAD

**Issue by JWorthe** [caeg-industries/crates.io#2]
Update what crates.io considers to be valid crate names so that they accept the separator character (start with the separator character being / but we’d like this to be configurable somehow; a hardcoded variable in one spot is fine)

- Ensure you can publish a crate whose name contains the separator to your local crates.io
- the cargo publish command should succeed, it should be viewable through the frontend on the homepage and by going to localhost:port/crates/mycrate[separator]subcrate
- it should be committed to the index in the [registry index trie](https://doc.rust-lang.org/nightly/cargo/reference/registries.html#index-format) by representing subpackages by placing foo/bar in foo@/bar, placed next to where foo is in the trie (i.e. the full path will be fo/foo@/bar).

**Comment by stephanbuys** [comment]
@JWorthe a starting point for the name validation: https://github.com/caeg-industries/crates.io/blob/subcrates/src/views/krate_publish.rs#L77

**Comment by JWorthe** [comment]
I've started with the validation side of this. It's now possible to do the 'cargo publish' side and get a successful response. In other words, the crate is uploaded to the registry. Here are the current next known issues to get this working properly.

- [x] The tarball being uploaded is foo_bar.crate (foo/bar.crate isn't a valid filename). This will probably need to continue to be the case. To get here, I had to update the code that checks the .crate file's name to allow this. I need to make sure that this doesn't accidentally let `foo/bar` overwrite `foo_bar`'s code.

- [x] The frontend shows the new subcrate (YAY!), but you can't navigate to a detailed view (the slash confuses the frontend's routing).
- [x] I haven't updated the registry index trie yet, so subcrates will conflict with their parents (you could say this feature is currently a teenager).
- [x] The S3 path for the subcrate is currently crates/foo/bar/foo/bar-1.0.0.crate. Based on the .crate file name while uploading, this should probably be crates/foo/foo_bar-1.0.0.crate

**Comment by JWorthe** [comment]
I think I can call this one done now!

Some implementation notes:
- I needed two different separators for namespaces to make this work. One to be the canonical separator (`/`) and one to be a "filename-safe" separator that I can use in filenames and URLs (`~`) since slash really doesn't work well there.
  - Files in particular appear as the tarballs uploading by `cargo publish`.
  - I chose to use the filename safe separator everywhere on the API because it was difficult to keep the existing API endpoints working the same way and disambiguate routes. For example, without changing the separators, `/api/v1/crates/foo/versions` could either mean get all info about subcrate `foo/version` or get the versions for crate `foo`. With the filename safe separator, this API call is to `/api/v1/crates/foo~versions`.
  - The separators are controlled by constants in `src/models/krate.rs` for Rust code and `app/utils/subcrate.js` for Javascript.
- Introducing subcrates effectively doubles the maximum name of crate names allowed in crates.io from 64 characters to 129 (64 each for namespace and subcrate, 1 for separator).
- Some parts of the frontend try to find docs.rs URLs. Those calls are using the filename safe separators, but docs.rs has not been changed at all to accommodate this.
